import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, BookOpen } from 'lucide-react';
import type { Message, Book } from './types';
import { app, getInitialState } from './agent/graph';

// Simple Book Card Component
const BookCard = ({ book }: { book: Book }) => {
  return (
    <div className="book-card">
      <img src={book.coverImage} alt={book.title} className="book-cover" />
      <div className="book-info">
        <span className="book-genre">{book.genre}</span>
        <h4 className="book-title">{book.title}</h4>
        <p className="book-author">by {book.author}</p>
        
        {/* We parse the description and reason back out (from the hack in graph.ts) */}
        {book.description.includes('*Why it matches:') ? (
          <>
            <p className="text-sm text-gray-600 line-clamp-3">
              {book.description.split('\n\n*Why it matches:')[0]}
            </p>
            <p className="book-reason">
              {book.description.split('*Why it matches: ')[1].replace('*', '')}
            </p>
          </>
        ) : (
          <p className="text-sm text-gray-600 line-clamp-4">{book.description}</p>
        )}
      </div>
    </div>
  );
};

function App() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      role: 'bot',
      content: "Hi! I'm BookBuddy, your personal AI librarian. What kind of book are you in the mood for today?"
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  // Track LangGraph State
  const [graphState, setGraphState] = useState(getInitialState());

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (text: string = inputValue) => {
    if (!text.trim()) return;

    const newUserMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: text
    };

    setMessages(prev => [...prev, newUserMessage]);
    setInputValue('');
    setIsTyping(true);

    // Prepare input for the graph
    const inputs = {
      messages: [...graphState.messages, newUserMessage],
      preferences: graphState.preferences,
      recommendationCount: graphState.recommendationCount
    };

    try {
      // Run the graph
      const result = await app.invoke(inputs);
      
      // Update local React state with the graph's new state
      setGraphState(result as any);
      
      const typedResult = result as { messages: Message[] };
      // Get the latest message generated by the graph (the bot's response)
      const botMessage = typedResult.messages[typedResult.messages.length - 1];
      
      // Simulate network/typing delay
      setTimeout(() => {
        setMessages(prev => [...prev, botMessage]);
        setIsTyping(false);
      }, 600);

    } catch (error) {
      console.error("Error invoking graph:", error);
      setIsTyping(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const suggestedPrompts = [
    "Recommend me a fantasy book",
    "I want something emotional",
    "Give me a mystery",
    "Surprise me"
  ];

  return (
    <div className="app-container">
      <div className="chat-container">
        
        {/* Header */}
        <div className="chat-header">
          <div className="header-icon">
            <BookOpen size={24} />
          </div>
          <div>
            <h1 className="chat-title">BookBuddy</h1>
            <p className="chat-subtitle">AI Book Recommendations</p>
          </div>
        </div>

        {/* Messages Area */}
        <div className="chat-messages">
          {messages.map((msg) => (
            <div key={msg.id} className={`message-wrapper ${msg.role}`}>
              {msg.role === 'bot' && (
                <div className="message-avatar">
                  <Bot size={18} />
                </div>
              )}
              
              <div className={msg.role === 'bot' ? 'bot-container flex-col' : ''}>
                <div className={`message ${msg.role}`}>
                  {msg.content}
                </div>
                
                {/* Render Book Recommendations if present */}
                {msg.recommendations && (
                  <div className="recommendations">
                    {msg.recommendations.map(book => (
                      <BookCard key={book.id} book={book} />
                    ))}
                  </div>
                )}
              </div>

              {msg.role === 'user' && (
                <div className="message-avatar" style={{ marginLeft: '12px', marginRight: 0, backgroundColor: 'var(--primary-color)' }}>
                  <User size={18} />
                </div>
              )}
            </div>
          ))}
          
          {isTyping && (
            <div className="message-wrapper bot">
              <div className="message-avatar">
                <Bot size={18} />
              </div>
              <div className="message bot">
                <div className="typing-indicator">
                  <div className="typing-dot"></div>
                  <div className="typing-dot"></div>
                  <div className="typing-dot"></div>
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="chat-input-container">
          {messages.length <= 2 && (
            <div className="suggested-prompts">
              {suggestedPrompts.map(prompt => (
                <button 
                  key={prompt}
                  className="prompt-chip"
                  onClick={() => handleSend(prompt)}
                >
                  {prompt}
                </button>
              ))}
            </div>
          )}
          
          <div className="input-form">
            <input
              type="text"
              className="chat-input"
              placeholder="Ask for a recommendation..."
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={isTyping}
            />
            <button 
              className="send-button"
              onClick={() => handleSend()}
              disabled={!inputValue.trim() || isTyping}
            >
              <Send size={18} />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}

export default App;
